name: Zenon.Sdk.NET

on:
  push:
    branches:
      - main
      - ledger

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - name: Setup Nerdbank.GitVersioning
      uses: dotnet/nbgv@v0.4.0
      with:
        setAllVars: true
    - name: Restore
      run: dotnet restore src/Zenon.Sdk.sln
    - name: Build
      run: dotnet build src/Zenon.Sdk.sln --no-restore
    - name: Test
      run: dotnet test src/Zenon.Sdk.sln --no-build --verbosity normal --collect:"XPlat Code Coverage"
    - name: Pack
      run: dotnet pack src/Zenon.Sdk.sln
    - name: Publish
      run: dotnet nuget push packages/*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json
    - name: Codecov
      uses: codecov/codecov-action@v3.1.0
      with:
        directory: src/Zenon.Tests/TestResults
        flags: unittests
        verbose: true
